### ISSUE TITLE
Cumulative consumption for today

### ISSUE THREAD

**Issue by danmed** [cybermaggedon/pyglowmarkt#1]
Hey, great job on this.. it's almost exactly what I'm looking for however what i need is a cumulative consumption for today..

I thought this line would do what i was after : 

`glowmarkt-csv  -u 'username' -p 'password' -m 1440 -d P1D -c electricity.consumption`

Which outputs : 

DCC Sourced,717ebe55-d14c-423a-80f7-55ef78aa45bf,2021-09-06T01:00:00,4.165,kWh
DCC Sourced,717ebe55-d14c-423a-80f7-55ef78aa45bf,2021-09-07T01:00:00,23.508,kWh

Which is very nearly correct.. except.. it's running from 1am and not 00:00 and i need it to ONLY read today

**Comment by danmed** [comment]
So.. i've worked on this a little in bash.. and i've gotten.. somewhere.. 

`#!/bin/bash

since_midnight=$(( $(date "+10#%H * 60 + 10#%M") ))
/root/glowmarkt-csv  -u 'username' -p 'password' -m $since_midnight -d P1D -c electricity.consumption > consumption.csv
while read line
do
   echo $line
done < <(tail -n +2 consumption.csv)
`

This (with a modified version of glowmarkt-csv) will just output me 2 values.. i just need to find a way to add these together :)

**Comment by danmed** [comment]
OK, think i've got it : 
https://github.com/danmed/Glow2MQTT

**Comment by cybermaggedon** [comment]
@danmed thanks for taking an interest.  Regarding...

> Which is very nearly correct.. except.. it's running from 1am and not 00:00 and i need it to ONLY read today

I'll try this out in a sec and check. My PC is overheating from the weather X-D.  It's probably something to do with timezones, midnight GMT == 1am BST.  Maybe I need to tighten up the timezone handling.

**Comment by danmed** [comment]
Hi there, if it's working as intended, then don't worry :) the script i linked to above deals with it by adding the values together and it seems to line up with the bright app.

**Comment by cybermaggedon** [comment]
@danmed Oh cool! That's to push out MQTT messages?  Would that work with Home Assistant?

I am gonna check the timezone handling. It's something I've consistently got wrong throughout my coding career.

**Comment by danmed** [comment]
Hey, yes that's exactly what i'm using it for.. to integrate it into the HA Energy Dashboard :)

  - platform: mqtt
    name: glow_energy_today
    state_topic: "glowmarkt/consumptiontoday"
    unit_of_measurement: 'kWh'  
    device_class: energy
    state_class: total_increasing

**Comment by danmed** [comment]
Btw, i've posted my github all over the place.. hopefully it'll drive a handful of people my way and as a result to your repo..

I've credited you in my readme, hopefully that's the correct way to do things.. I noticed you didn't have a license applied to yours so i didn't apply one to mine.. i wasn't sure how that works or what i should select..

If i'm stepping on any licensing you do have please let me know!

**Comment by cybermaggedon** [comment]
Oh, great, appreciate the reference.

Good point on the licence, I don't have a strong opinion. I would usually put Apache licence on something like this, so I'll add that. If you would prefer a different licence let me know.

**Comment by cybermaggedon** [comment]
Apache 2 licence added

**Comment by danmed** [comment]
> Apache 2 licence added

Done the same.. thanks.

**Comment by cybermaggedon** [comment]
@danmed I played around with a couple of things.  The timezone handling wasn't right, times were being shifted by 1 hour incorrectly in summer time, but not winter time.  That's fixed. The times reported in the output are in local time.  As far as I can tell, Bright does everything with reference to midnight GMT when you ask for 1 day's worth of data, which is why you see the 01:00 time.

I also added rounding of times, so if you ask for P1H intervals, the from/to times are rounded to the nearest number. This seems to make the reported numbers closer to what you'd see in the Bright app.

```
$ glowmarkt-csv -u user -p pass -m 3800 -d P1D -c electricity.consumption
entity,resource,time,value,unit
DCC Sourced,a3e4401e-0e0e-495d-abf1-e7d6d5405bdb,2021-09-07T01:00:00,11.896,kWh
DCC Sourced,a3e4401e-0e0e-495d-abf1-e7d6d5405bdb,2021-09-08T01:00:00,9.903,kWh
DCC Sourced,a3e4401e-0e0e-495d-abf1-e7d6d5405bdb,2021-09-09T01:00:00,0.382,kWh
```

But you can ask for GMT. This only changes how the time is reported on output.
```
$ env TZ=GMT glowmarkt-csv -u user -p pass -m 3800 -d P1D -c electricity.consumption
entity,resource,time,value,unit
DCC Sourced,a3e4401e-0e0e-495d-abf1-e7d6d5405bdb,2021-09-07T00:00:00,12.265,kWh
DCC Sourced,a3e4401e-0e0e-495d-abf1-e7d6d5405bdb,2021-09-08T00:00:00,9.903,kWh
DCC Sourced,a3e4401e-0e0e-495d-abf1-e7d6d5405bdb,2021-09-09T00:00:00,0.127,kWh
```

**Comment by cybermaggedon** [comment]
@danmed one more tweak you might be interested in...
```
$ glowmarkt-today -u user -p pass -c electricity.consumption
3.998
```

**Comment by danmed** [comment]
> @danmed one more tweak you might be interested in...
> 
> ```
> $ glowmarkt-today -u user -p pass -c electricity.consumption
> 3.998
> ```

wow.. that would make things much easier.. however.. i'm getting an incorrect value.. I'm seeing 14.1 as my actual usage.. but that command returns 11.5.. i thin it's now missing the first 2 hours of the day :(

I've significantly reduced my bash script to like 2 lines now lol.. so thank you.. just need to figure out why the value is wrong..

**Comment by danmed** [comment]
in fact.. glowmarkt-csv is just giving me "request failed" now :(

**Comment by danmed** [comment]
So with glowmarkt-csv there appears to be a problem with the periods : 

glowmarkt-csv  -u user -p pass -m 240 -d **P1D** -c electricity.consumption
Request failed

glowmarkt-csv  -u user -p pass -m 240 -d **PT1H** -c electricity.consumption
entity,resource,time,value,unit
DCC Sourced,717ebe55-d14c-423a-80f7-55ef78aa45bf,2021-09-09T09:00:00,0.753,kWh
DCC Sourced,717ebe55-d14c-423a-80f7-55ef78aa45bf,2021-09-09T10:00:00,0.843,kWh
DCC Sourced,717ebe55-d14c-423a-80f7-55ef78aa45bf,2021-09-09T11:00:00,0.764,kWh
DCC Sourced,717ebe55-d14c-423a-80f7-55ef78aa45bf,2021-09-09T12:00:00,0.74,kWh

**Comment by cybermaggedon** [comment]
Hmmm, OK. I think there are problems if the duration specified by -m is too short.  Try a longer value?

**Comment by cybermaggedon** [comment]
I'm taking a look at the query I'm doing, something still not right.

**Comment by danmed** [comment]
no worries, i've gotten my script going again with the glowmarkt-csv using this command : 

glowmarkt-csv  -u 'user' -p 'pass' -m $since_midnight -d PT30M -c electricity.consumption -n

That gives me the correct numbers.. but i'm using a modified glowmarkt-csv that removes the other columns and only prints out the one I need.

However, if you can figure out the glowmarkt-today then all this is no longer necessary :)

Edit : This is the command i'm using to figure out how long has passed since mindnight and pass that to -m... not sure if its any help to you 

`since_midnight=$(( $(date "+10#%H * 60 + 10#%M") ))`

**Comment by cybermaggedon** [comment]
The query I'm doing is wrong for some reason.  Timezones are weird. :/  I'll work it out.

**Comment by cybermaggedon** [comment]
Right... I think I've got it right this time.  Sorry for being slow. To get the right result you need to get the API working in your local timezone. 🤦

glowmarkt-today is giving me the data I see in the app now.  The hourly and 30M readings match up also.

**Comment by danmed** [comment]
> Right... I think I've got it right this time. Sorry for being slow. To get the right result you need to get the API working in your local timezone. 🤦
> 
> glowmarkt-today is giving me the data I see in the app now. The hourly and 30M readings match up also.

Lol hardly slow!!

I just did a pip install pyglowmarkt --upgrade but i don't think it pulled anything down.


Ah! there we go.. yes.. glowmarkt-today is now returning the correct value.. nicely done!.. now i can drop everything i changed about yours and just send that value to mqtt..

**Comment by cybermaggedon** [comment]
Yeh, I just pushed to PyPI version 0.4.  Glad it's working!  Weekly / monthly are not going to match what's in the app, and I can't work out what periods it's actually using.  This is stuff I'd really like to see in HA, so appreciate you've looked at this.

**Comment by danmed** [comment]
no problem, to be honest, now that you've made this work.. i've really done nothing :)

my github will now consist of a single shell script with a couple of lines lol

**Comment by danmed** [comment]
I've been toying with (attempting to) create a docker container to do this.. but seeing as it's 99% your work.. would you ever consider adding the MQTT capability to your code?

If not, that's cool, ill beef up my stuff to use environment variables and see if i can get it working.. it obviously all depends on your code though so any changes you have to make due to the api or whatever i'd have to take into consideration with the shell script.

Edit : i've just looked up mqtt in python.. and wow.. it looks like a right git.. (but then i don't know python)

**Comment by cybermaggedon** [comment]
Yeh, happy to take a look, got some time next week. Glad of whatever guidance or pointers you have.

**Comment by cybermaggedon** [comment]
@danmed, I have a variant of glowmarkt-today, which can be used like this...
```
scripts/glowmarkt-mqtt -u GLOWMARKT-USER -p GLOWMARKT-PASS \
    -c electricity.consumption -t glowmarkt/consumption \
    -h localhost -U MQTT-USER -P MQTT-PASS
```
Does that do what you want?

**Comment by danmed** [comment]
Hey, so i was getting a paho error but i sorted that by installing it :)

But now it just keeps telling me the switches..

glowmarkt-mqtt -u user -p pass -c electricity.consumption -t glowmarkt1/consumption -h 192.168.2.15 -u mqtt2 -p mqtt2

`usage: glowmarkt-mqtt [-h] --username USERNAME --password PASSWORD [--classifier CLASSIFIER] [--mqtt-hostname MQTT_HOSTNAME] [--mqtt-username MQTT_USERNAME]
                      [--mqtt-password MQTT_PASSWORD] [--topic TOPIC]

optional arguments:
  -h, --help            show this help message and exit
  --username USERNAME, -u USERNAME
                        Bright account username
  --password PASSWORD, -p PASSWORD
                        Bright account password
  --classifier CLASSIFIER, -c CLASSIFIER
                        Resource classifier to use (default: electricity.consumption)
  --mqtt-hostname MQTT_HOSTNAME, --host MQTT_HOSTNAME
                        MQTT hostname (default: localhost)
  --mqtt-username MQTT_USERNAME, -U MQTT_USERNAME
                        MQTT username
  --mqtt-password MQTT_PASSWORD, -P MQTT_PASSWORD
                        MQTT password
  --topic TOPIC, -t TOPIC
                        MQTT topic to publish to (default: glowmarkt/consumption)

**Comment by cybermaggedon** [comment]
@danmed, :)

Sorry, gave you duff information, the `-h` flag calls up the help page.  Try `--host`

**Comment by danmed** [comment]
@cybermaggedon lol no worries, 

OK changed that and now i'm getting an authentication error

glowmarkt-mqtt: error: unrecognized arguments: --mqtt_username mqtt --mqtt_password mqtt

**Comment by cybermaggedon** [comment]
@danmed try `--mqtt-username` instead of `--mqtt_username`, same with password option?

**Comment by danmed** [comment]
@cybermaggedon lol that works.. stupid fat fingers on my end..

and yes, that does exactly what i was doing with the shell script! so that's perfect!

Assume it'll do cost too?

**Comment by cybermaggedon** [comment]
@danmed, Awesome!  Yes, you need to add `-c electricity.consumption.cost` for the cost. And `-t topic` to send it to a different topic.

**Comment by danmed** [comment]
Updated my shell script to make it easily cronable, thanks again!
