### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by HandyHat** [cybermaggedon/pyglowmarkt#13]
Hey @cybermaggedon, thank you so much for the library!
I've recently implemented it in https://github.com/HandyHat/ha-hildebrandglow-dcc and it's been working great.

I was wondering if it would be possible for you to release a new version so that we can use the newer features, such as the support for Nulls?

Thanks!

**Comment by cybermaggedon** [comment]
Apologies, been a lot going on, this is the latest master, tagged `v0.5.5`, does that do what you need?

https://pypi.org/project/pyglowmarkt/0.5.5/

**Comment by cybermaggedon** [comment]
Great project, btw!

**Comment by HandyHat** [comment]
No worries - that's perfect. Thanks!
