### ISSUE TITLE
Standing Charge

### ISSUE THREAD

**Issue by totalitarian** [cybermaggedon/pyglowmarkt#5]
Hi, love this library!

Any way to extract the standing charge value or even better, add it to the costs for today?

**Comment by cybermaggedon** [comment]
Thanks @totalitarian!  Yes, the standing charge is available in the Glowmarkt service, and it's dumped out when you run `glowmarkt-dump`.  I'll see if I can work out a way to add it.

**Comment by cybermaggedon** [comment]
@totalitarian I added the -S option to `glowmarkt-today` in 0.5.2. Does that do what you want? e.g.
```
glowmarkt-today -u $user -p $pass -c electricity.consumption.cost -S
```

**Comment by totalitarian** [comment]
Perfect!
